name: Emoji
main: net.pomdre.emoji.Main
version: 4.5.2
description: Simple emojis in the chat and on sign 50+ ⚔️ No texture pack!
author: Pomdre
website: https://www.spigotmc.org/resources/emoji%E2%9D%A4.61432/
commands:
    emoji:
        aliases: [emoji]
        permissions:
            emoji.chat:
            default: op
            emoji.list:
            default: op
            emoji.help:
            default: op
            emoji.sign:
            default: op
            emoji.shortcuts:
            default: op
        description: "You can use: /emoji list"
        permission-message: You do not have have permission to use this command.
        usage: "You can use: /emoji list"