#
# +------------------------------------------------------+ #
# |                 Emoji                                | #
# +------------------------------------------------------+ #
#
# Coloor list
# &0	BLACK
# &1	DARK BLUE
# &2	DARK GREEN
# &3	DARK AQUA
# &4	DARK RED
# &5	DARK PURPLE 
# &6	GOLD
# &7	GRAY
# &8	DARK GRAY
# &9	INDIGO
# &A    GREEN
# &B	AQUA
# &C	RED
# &D	PINK
# &E	YELLOW
# &F	WHITE
# &M	STRIKE THROUGH
# &N	UNDERLINED
# &L	BOLD
# &K	RANDOM
# &O	ITALIC
# &r     RESET
#
# Use in chat
chat: true
#
# Shortcuts for emojis
shortcuts: true
#
# Use on signs
sign: true
#
# How many pages to display under /emoji list
pagesperpage: 20
#
# Change the % symbols surrounding the emoji name
surrounding: '%'
#
# Use metrics
metrics: true
#
# Here you can choose the color of Emoji
black_sun_with_rays: '&E'
cloud: '&7'
umbrella: '&r'
snowman: '&F'
comet: '&r'
black_star: '&r'
white_star: '&r'
lightning: '&r'
thunderstorm: '&r'
sun: '&r'
ascending_node: '&r'
descending_node: '&r'
conjunction: '&r'
opposition: '&r'
black_telephone: '&r'
white_telephone: '&r'
ballot_box: '&r'
ballot_box_with_check: '&r'
ballot_box_with_x: '&r'
saltire: '&r'
reversed_rotated_floral_heart_bullet: '&r'
black_left_pointing_index: '&r'
black_right_pointing_index: '&r'
white_left_pointing_index: '&r'
white_up_pointing_index: '&r'
white_right_pointing_index: '&r'
white_down_pointing_index: '&r'
skull_and_crossbones: '&r'
caution_sign: '&r'
radioactive_sign: '&r'
biohazard_sign: '&r'
caduceus: '&r'
ankh: '&r'
orthodox_cross: '&r'
chi_rho: '&r'
cross_of_lorraine: '&r'
cross_of_jerusalem: '&r'
star_and_crescent: '&r'
farsi_symbol: '&r'
adi_shakti: '&r'
hammer_and_sickle: '&r'
peace_symbol: '&r'
yin_yang: '&r'
trigram_for_heaven: '&r'
trigram_for_lake: '&r'
trigram_for_fire: '&r'
trigram_for_thunder: '&r'
trigram_for_wind: '&r'
trigram_for_water: '&r'
trigram_for_mountain: '&r'
trigram_for_earth: '&r'
wheel_of_dharma: '&r'
white_frowning_face: '&r'
white_smiling_face: '&r'
black_smiling_face: '&r'
white_sun_with_rays: '&r'
first_quarter_moon: '&r'
last_quarter_moon: '&r'
mercury: '&r'
female_sign: '&r'
earth: '&r'
male_sign: '&r'
jupiter: '&r'
saturn: '&r'
uranus: '&r'
neptune: '&r'
pluto: '&r'
aries: '&r'
taurus: '&r'
gemini: '&r'
cancer: '&r'
leo: '&r'
virgo: '&r'
libra: '&r'
scorpius: '&r'
sagittarius: '&r'
capricorn: '&r'
aquarius: '&r'
pisces: '&r'
white_chess_king: '&r'
white_chess_queen: '&r'
white_chess_rook: '&r'
white_chess_bishop: '&r'
white_chess_knight: '&r'
white_chess_pawn: '&r'
black_chess_king: '&r'
black_chess_queen: '&r'
black_chess_rook: '&r'
black_chess_bishop: '&r'
black_chess_knight: '&r'
black_chess_pawn: '&r'
black_spade_suit: '&r'
white_heart_suit: '&c'
white_diamond_suit: '&r'
black_club_suit: '&r'
white_spade_suit: '&r'
black_heart_suit: '&c'
black_diamond_suit: '&r'
white_club_suit: '&r'
hot_springs: '&r'
quarter_note: '&r'
eighth_note: '&r'
beamed_eighth_notes: '&r'
beamed_sixteenth_notes: '&r'
music_flat_sign: '&r'
music_natural_sign: '&r'
music_sharp_sign: '&r'
west_syriac_cross: '&r'
east_syriac_cross: '&r'
#
# Extra
white_draughts_man: '&r'
white_draughts_king: '&r'
black_draughts_man: '&r'
black_draughts_king: '&r'
#
# Suffix
suffix_black_sun_with_rays: '&r'
suffix_cloud: '&r'
suffix_umbrella: '&r'
suffix_snowman: '&r'
suffix_comet: '&r'
suffix_black_star: '&r'
suffix_white_star: '&r'
suffix_lightning: '&r'
suffix_thunderstorm: '&r'
suffix_sun: '&r'
suffix_ascending_node: '&r'
suffix_descending_node: '&r'
suffix_conjunction: '&r'
suffix_opposition: '&r'
suffix_black_telephone: '&r'
suffix_white_telephone: '&r'
suffix_ballot_box: '&r'
suffix_ballot_box_with_check: '&r'
suffix_ballot_box_with_x: '&r'
suffix_saltire: '&r'
suffix_reversed_rotated_floral_heart_bullet: '&r'
suffix_black_left_pointing_index: '&r'
suffix_black_right_pointing_index: '&r'
suffix_white_left_pointing_index: '&r'
suffix_white_up_pointing_index: '&r'
suffix_white_right_pointing_index: '&r'
suffix_white_down_pointing_index: '&r'
suffix_skull_and_crossbones: '&r'
suffix_caution_sign: '&r'
suffix_radioactive_sign: '&r'
suffix_biohazard_sign: '&r'
suffix_caduceus: '&r'
suffix_ankh: '&r'
suffix_orthodox_cross: '&r'
suffix_chi_rho: '&r'
suffix_cross_of_lorraine: '&r'
suffix_cross_of_jerusalem: '&r'
suffix_star_and_crescent: '&r'
suffix_farsi_symbol: '&r'
suffix_adi_shakti: '&r'
suffix_hammer_and_sickle: '&r'
suffix_peace_symbol: '&r'
suffix_yin_yang: '&r'
suffix_trigram_for_heaven: '&r'
suffix_trigram_for_lake: '&r'
suffix_trigram_for_fire: '&r'
suffix_trigram_for_thunder: '&r'
suffix_trigram_for_wind: '&r'
suffix_trigram_for_water: '&r'
suffix_trigram_for_mountain: '&r'
suffix_trigram_for_earth: '&r'
suffix_wheel_of_dharma: '&r'
suffix_white_frowning_face: '&r'
suffix_white_smiling_face: '&r'
suffix_black_smiling_face: '&r'
suffix_white_sun_with_rays: '&r'
suffix_first_quarter_moon: '&r'
suffix_last_quarter_moon: '&r'
suffix_mercury: '&r'
suffix_female_sign: '&r'
suffix_earth: '&r'
suffix_male_sign: '&r'
suffix_jupiter: '&r'
suffix_saturn: '&r'
suffix_uranus: '&r'
suffix_neptune: '&r'
suffix_pluto: '&r'
suffix_aries: '&r'
suffix_taurus: '&r'
suffix_gemini: '&r'
suffix_cancer: '&r'
suffix_leo: '&r'
suffix_virgo: '&r'
suffix_libra: '&r'
suffix_scorpius: '&r'
suffix_sagittarius: '&r'
suffix_capricorn: '&r'
suffix_aquarius: '&r'
suffix_pisces: '&r'
suffix_white_chess_king: '&r'
suffix_white_chess_queen: '&r'
suffix_white_chess_rook: '&r'
suffix_white_chess_bishop: '&r'
suffix_white_chess_knight: '&r'
suffix_white_chess_pawn: '&r'
suffix_black_chess_king: '&r'
suffix_black_chess_queen: '&r'
suffix_black_chess_rook: '&r'
suffix_black_chess_bishop: '&r'
suffix_black_chess_knight: '&r'
suffix_black_chess_pawn: '&r'
suffix_black_spade_suit: '&r'
suffix_white_heart_suit: '&r'
suffix_white_diamond_suit: '&r'
suffix_black_club_suit: '&r'
suffix_white_spade_suit: '&r'
suffix_black_heart_suit: '&r'
suffix_black_diamond_suit: '&r'
suffix_white_club_suit: '&r'
suffix_hot_springs: '&r'
suffix_quarter_note: '&r'
suffix_eighth_note: '&r'
suffix_beamed_eighth_notes: '&r'
suffix_beamed_sixteenth_notes: '&r'
suffix_music_flat_sign: '&r'
suffix_music_natural_sign: '&r'
suffix_music_sharp_sign: '&r'
suffix_west_syriac_cross: '&r'
suffix_east_syriac_cross: '&r'
#
# Suffix Extra
suffix_white_draughts_man: '&r'
suffix_white_draughts_king: '&r'
suffix_black_draughts_man: '&r'
suffix_black_draughts_king: '&r'
